language: python
dist: xenial
#branches:
#  only:
#    - packaging
#    - master
services:
  - xvfb
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "3.6"
install:
  - sudo apt-get update
  - sudo apt install libdb-dev python3-bsddb3
  # Used for tree_plot
  - sudo apt-get install graphviz
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Replace dep1 dep2 ... with your dependencies
#  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION dep1 dep2 ...
#  - conda activate test-environment
#  - python setup.py install
  - source $(conda info --root)/etc/profile.d/conda.sh
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - conda activate test-environment
  - conda info -a
  # Install garage and dependencies
  - cd third_party/garage
  - touch mjkey.txt
  - echo "hello" > mjkey.txt
  - ./scripts/setup_linux.sh --mjkey mjkey.txt --modify-bashrc
  - rm mjkey.txt
  - pip install --ignore-installed garage
#  - pip install -e .[dev]
  - pip install numpy==1.14.5 gym python-dateutil dowel joblib cached_property akro glfw pyprind cma bsddb3 fire depq compress_pickle
# Install the codecov pip dependency
  - pip install codecov pytest pytest-cov
#  - pip install rlgarage
  # Used for tree_plot
  - pip install pydot

  # Run AST setup
  - conda info -a
  - cd ../../
  - source scripts/setup.sh

script:
  # Your test script goes here
  - conda info -a
#  - python examples/validate_install.py
# Run the unit test
#  - coverage run examples/tests/unit_tests.py
#  - travis_wait 30 pytest --cov=ast_toolbox --cov=examples tests/unit_tests.py
  - travis_wait 30 pytest --cov-config=.coveragerc tests/unit_tests.py

# Push the results back to codecov
after_success:
  - codecov